# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'field_mapping.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot

class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(600, 20, 621, 511))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.widget = QtWidgets.QWidget(self.frame_5)
        self.widget.setGeometry(QtCore.QRect(0, 0, 611, 511))
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.tableView_6 = QtWidgets.QTableView(self.widget)
        self.tableView_6.setAlternatingRowColors(True)
        self.tableView_6.setObjectName("tableView_6")
        self.gridLayout_7.addWidget(self.tableView_6, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_13.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_13.addWidget(self.pushButton_17)
        self.backButton_9 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.backButton_9.setFont(font)
        self.backButton_9.setObjectName("backButton_9")
        self.horizontalLayout_13.addWidget(self.backButton_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(20, 20, 561, 511))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.widget1 = QtWidgets.QWidget(self.frame_6)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 561, 511))
        self.widget1.setObjectName("widget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.browseButton_3 = QtWidgets.QPushButton(self.widget1)
        self.browseButton_3.setObjectName("browseButton_3")
        self.gridLayout_3.addWidget(self.browseButton_3, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.sheetNamelineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        self.sheetNamelineEdit_3.setText("")
        self.sheetNamelineEdit_3.setObjectName("sheetNamelineEdit_3")
        self.gridLayout_3.addWidget(self.sheetNamelineEdit_3, 1, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_5.addWidget(self.comboBox, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_5.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_5.addWidget(self.comboBox_4, 0, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_5.addWidget(self.checkBox_4, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_5.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_5.addWidget(self.checkBox_5, 1, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_5.addWidget(self.comboBox_5, 1, 3, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_5.addWidget(self.checkBox_7, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_5.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_5.addWidget(self.checkBox_8, 2, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_5.addWidget(self.comboBox_6, 2, 3, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_5.addWidget(self.checkBox_13, 3, 0, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_5.addWidget(self.comboBox_13, 3, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_5.addWidget(self.checkBox_14, 3, 2, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout_5.addWidget(self.comboBox_14, 3, 3, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_5.addWidget(self.checkBox_15, 4, 0, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_15.setObjectName("comboBox_15")
        self.gridLayout_5.addWidget(self.comboBox_15, 4, 1, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_5.addWidget(self.checkBox_16, 4, 2, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_16.setObjectName("comboBox_16")
        self.gridLayout_5.addWidget(self.comboBox_16, 4, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(240, 600, 711, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(20, 539, 1201, 41))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_14.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_14.addWidget(self.pushButton_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Fleet Inventory Template"))
        self.pushButton_16.setText(_translate("MainWindow", "Load Data Preview"))
        self.pushButton_17.setText(_translate("MainWindow", "Load Data Full"))
        self.backButton_9.setText(_translate("MainWindow", "Clear"))
        self.label_9.setText(_translate("MainWindow", "File Name"))
        self.browseButton_3.setText(_translate("MainWindow", "Browse"))
        self.label_10.setText(_translate("MainWindow", "Sheet Name"))
        self.label.setText(_translate("MainWindow", "Select Customer Fields Below:"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_7.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_8.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_13.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_14.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_15.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_16.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Download Data"))
        self.pushButton_3.setText(_translate("MainWindow", "Scrub Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

